#!/bin/sh
# nexus-screensaver.sh — auto-generated by nexus-screensaver-ctl.sh
# DO NOT EDIT — run nexus-screensaver-ctl.sh to configure

SAVERS="cacafire asciiquarium cbonsai cmatrix tty-clock nyancat bb"
COUNT=7

PICK=$(( $(od -An -N1 -tu1 /dev/urandom | tr -d ' ') % COUNT + 1 ))
SAVER=$(echo "$SAVERS" | tr ' ' '\n' | sed -n "${PICK}p")

case "$SAVER" in
    cacafire)     exec cacafire ;;
    asciiquarium) exec asciiquarium ;;
    cbonsai)      exec cbonsai -l -t 0.05 ;;
    cmatrix)      exec cmatrix -s -C cyan ;;
    tty-clock)    exec tty-clock -s -c -C 6 ;;
    nyancat)      exec nyancat ;;
    bb)           exec bb ;;
    sl)           exec sl -al ;;
    pipes.sh)     exec pipes.sh ;;
    *)            exec cmatrix -s ;;
esac
