#!/bin/sh
# nexus-screensaver-ctl.sh — NeXuS Terminal Screensaver Controller
# Sane • Simple • Secure • Beautiful
# Manages the random screensaver rotation for idle/lock sessions

CONFIG="$HOME/.config/nexus/screensaver.conf"
SAVER_SCRIPT="$HOME/scripts/nexus-screensaver.sh"

# ── Default config ────────────────────────────────────────────────────────────
DEFAULT_SAVERS="cacafire asciiquarium cbonsai cmatrix tty-clock nyancat bb sl pipes.sh"
DEFAULT_IDLE=120
DEFAULT_LOCK=180

# ── Load or create config ─────────────────────────────────────────────────────
load_config() {
    mkdir -p "$HOME/.config/nexus"
    if [ ! -f "$CONFIG" ]; then
        cat > "$CONFIG" << EOF
# NeXuS Screensaver Configuration
# Edit ENABLED to control the rotation — space separated
ENABLED="cacafire asciiquarium cbonsai cmatrix tty-clock nyancat bb"
IDLE_TIMEOUT=120
LOCK_TIMEOUT=180
EOF
    fi
    . "$CONFIG"
}

# ── Detect what's actually installed ─────────────────────────────────────────
detect_installed() {
    INSTALLED=""
    for saver in $DEFAULT_SAVERS; do
        if command -v "$saver" > /dev/null 2>&1; then
            INSTALLED="$INSTALLED $saver"
        fi
    done
    echo "$INSTALLED" | xargs
}

# ── Rebuild the screensaver picker script ─────────────────────────────────────
rebuild_saver() {
    load_config
    SAVERS="${ENABLED:-$(detect_installed)}"
    COUNT=$(echo "$SAVERS" | wc -w)

    cat > "$SAVER_SCRIPT" << SCRIPT
#!/bin/sh
# nexus-screensaver.sh — auto-generated by nexus-screensaver-ctl.sh
# DO NOT EDIT — run nexus-screensaver-ctl.sh to configure

SAVERS="$SAVERS"
COUNT=$COUNT

PICK=\$(( \$(od -An -N1 -tu1 /dev/urandom | tr -d ' ') % COUNT + 1 ))
SAVER=\$(echo "\$SAVERS" | tr ' ' '\n' | sed -n "\${PICK}p")

case "\$SAVER" in
    cacafire)     exec cacafire ;;
    asciiquarium) exec asciiquarium ;;
    cbonsai)      exec cbonsai -l -t 0.05 ;;
    cmatrix)      exec cmatrix -s -C cyan ;;
    tty-clock)    exec tty-clock -s -c -C 6 ;;
    nyancat)      exec nyancat ;;
    bb)           exec bb ;;
    sl)           exec sl -al ;;
    pipes.sh)     exec pipes.sh ;;
    *)            exec cmatrix -s ;;
esac
SCRIPT
    chmod +x "$SAVER_SCRIPT"
    echo "  Screensaver script rebuilt with: $SAVERS"
}

# ── Preview a screensaver ─────────────────────────────────────────────────────
preview() {
    SAVER="$1"
    echo "  Previewing $SAVER — press Ctrl+C to stop"
    sleep 1
    case "$SAVER" in
        cacafire)     cacafire ;;
        asciiquarium) asciiquarium ;;
        cbonsai)      cbonsai -l -t 0.05 ;;
        cmatrix)      cmatrix -s -C cyan ;;
        tty-clock)    tty-clock -s -c -C 6 ;;
        nyancat)      nyancat ;;
        bb)           bb ;;
        sl)           sl -al ;;
        pipes.sh)     pipes.sh ;;
        *)            echo "Unknown screensaver: $SAVER" ;;
    esac
}

# ── Show status ───────────────────────────────────────────────────────────────
show_status() {
    load_config
    INSTALLED=$(detect_installed)
    echo ""
    echo "  NeXuS Screensaver Status"
    echo "  ─────────────────────────────────────"
    echo "  Installed:  $INSTALLED"
    echo "  Enabled:    ${ENABLED:-$INSTALLED}"
    echo "  Idle after: ${IDLE_TIMEOUT:-$DEFAULT_IDLE}s"
    echo "  Lock after: ${LOCK_TIMEOUT:-$DEFAULT_LOCK}s"
    echo "  Config:     $CONFIG"
    echo ""
}

# ── Enable/disable a screensaver ──────────────────────────────────────────────
enable_saver() {
    load_config
    SAVER="$1"
    if echo "$ENABLED" | grep -qw "$SAVER"; then
        echo "  $SAVER already enabled"
    else
        ENABLED="$ENABLED $SAVER"
        sed -i "s|^ENABLED=.*|ENABLED=\"$(echo $ENABLED | xargs)\"|" "$CONFIG"
        rebuild_saver
        echo "  Enabled: $SAVER"
    fi
}

disable_saver() {
    load_config
    SAVER="$1"
    ENABLED=$(echo "$ENABLED" | tr ' ' '\n' | grep -vw "$SAVER" | tr '\n' ' ' | xargs)
    sed -i "s|^ENABLED=.*|ENABLED=\"$ENABLED\"|" "$CONFIG"
    rebuild_saver
    echo "  Disabled: $SAVER"
}

set_timeout() {
    load_config
    IDLE="$1"
    LOCK="$2"
    sed -i "s|^IDLE_TIMEOUT=.*|IDLE_TIMEOUT=$IDLE|" "$CONFIG"
    sed -i "s|^LOCK_TIMEOUT=.*|LOCK_TIMEOUT=$LOCK|" "$CONFIG"
    echo "  Idle: ${IDLE}s  Lock: ${LOCK}s"
    echo "  Restart swayidle to apply: pkill swayidle"
}

# ── Help ──────────────────────────────────────────────────────────────────────
show_help() {
    echo ""
    echo "  nexus-screensaver-ctl — NeXuS Screensaver Controller"
    echo ""
    echo "  Usage:"
    echo "    nexus-screensaver-ctl status              — show current config"
    echo "    nexus-screensaver-ctl list                — show installed savers"
    echo "    nexus-screensaver-ctl preview <name>      — preview a screensaver"
    echo "    nexus-screensaver-ctl enable  <name>      — add to rotation"
    echo "    nexus-screensaver-ctl disable <name>      — remove from rotation"
    echo "    nexus-screensaver-ctl timeout <idle> <lock> — set timeouts (seconds)"
    echo "    nexus-screensaver-ctl rebuild             — rebuild picker script"
    echo "    nexus-screensaver-ctl random              — run a random one now"
    echo ""
    echo "  Screensavers: cacafire asciiquarium cbonsai cmatrix tty-clock nyancat bb sl pipes.sh"
    echo ""
}

# ── Main ──────────────────────────────────────────────────────────────────────
case "$1" in
    status)              show_status ;;
    list)                echo "  Installed: $(detect_installed)" ;;
    preview)             preview "$2" ;;
    enable)              enable_saver "$2" ;;
    disable)             disable_saver "$2" ;;
    timeout)             set_timeout "$2" "$3" ;;
    rebuild)             rebuild_saver ;;
    random)              exec "$SAVER_SCRIPT" ;;
    *)                   show_help ;;
esac
